[package]
name = "qemu_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.13"
iced = "0.12.1"
regex = "1.10.6"
serde = "1.0.204"
serde_json = "1.0.122"
termcolor = "1.4.1"

[[bin]]
name = "qemu_cli"
path = "src/main.rs"
